trainset_3d: ['Human36M', 'MuCo']
trainset_2d: ['MSCOCO', 'CrowdPose','MPII']
testset: 'PW3D'

lr_dec_epoch: [4,6]
end_epoch: 10
lr: 0.0001
lr_backbone: 0.0001
lr_dec_factor: 10

crowd: True

finetune: True